# Generated by Django 4.2.16 on 2024-10-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Student_name", models.CharField(max_length=180, null=True)),
                ("username", models.CharField(max_length=180, null=True)),
                ("password", models.CharField(max_length=180, null=True)),
            ],
        ),
    ]
