# Generated by Django 4.2.16 on 2024-10-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="tutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(null=True)),
                ("password", models.CharField(null=True)),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("Mat", "Math"),
                            ("Sci", "Science"),
                            ("Eng", "English"),
                        ],
                        default="Eng",
                        max_length=3,
                    ),
                ),
            ],
        ),
    ]
