# Generated by Django 4.2.16 on 2024-10-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_tutor"),
    ]

    operations = [
        migrations.CreateModel(
            name="carosel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="carosel/")),
                ("alt_text", models.CharField(max_length=150)),
            ],
        ),
    ]
