# Generated by Django 4.2.16 on 2024-10-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_carosel"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutor",
            name="tutorname",
            field=models.CharField(default=2, max_length=180),
            preserve_default=False,
        ),
    ]
