# Generated by Django 4.2.16 on 2024-11-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_student_username_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutor",
            name="password",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="username",
            field=models.CharField(),
        ),
    ]
