# Generated by Django 4.2.16 on 2024-11-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_tutor_password_alter_tutor_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="Student_name",
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name="student",
            name="password",
            field=models.CharField(max_length=180),
        ),
    ]
