# Generated by Django 4.2.16 on 2025-01-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_test_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
