# Generated by Django 4.2.16 on 2025-01-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_test_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutor",
            name="date_of_birth",
            field=models.DateField(default="1980-12-12"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tutor",
            name="email",
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tutor",
            name="phone_number",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tutor",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
    ]
