# Generated by Django 4.2.16 on 2025-01-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_tutor_date_of_birth_tutor_email_tutor_phone_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("password", models.CharField(max_length=180)),
            ],
        ),
    ]
